steps:
# TODO: Switch kaniko back to "latest" after this issue is fixed: https://github.com/GoogleContainerTools/kaniko/issues/1791
- name: 'gcr.io/kaniko-project/executor@sha256:6ecc43ae139ad8cfa11604b592aaedddcabff8cef469eda303f1fb5afe5e3034'
  env: ['REVISION_ID=$REVISION_ID']
  args:
  - --destination=gcr.io/$PROJECT_ID/libraries.io:$REVISION_ID
  - --cache=true
  - --cache-ttl=336h
  - --build-arg=REVISION_ID
  timeout: 2400s
# copy the compiled assets from the docker container to the workspace to then push to GCS
- name: 'docker'
  args: ['run', '-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/libraries.io:$REVISION_ID', 'cp', '-R', '/libraries.io/public/assets/', '/workspace/']
  timeout: 2400s
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', '/workspace/assets/', 'gs://libraries-static-assets/']
  timeout: 2400s
timeout: 4800s
